// Code generated by tools/pathgen; DO NOT EDIT.
// Source: dependencies/neper/neper-api.yaml

package api

import "fmt"

// =============================================================================
// BASE PATHS
// =============================================================================

const (
	// Base API path
	APIBase = "/api/v1"

	// Auth
	AuthBase         = APIBase + "/auth"
	AuthAuthenticate = AuthBase + "/authenticate"
	AuthRefreshToken = AuthBase + "/refresh_token"
	AuthRegister     = AuthBase + "/register"
	AuthUserInfo     = AuthBase + "/userinfo"

	// Downloads
	DownloadsBase    = APIBase + "/downloads"
	DownloadStarsExe = DownloadsBase + "/stars.exe"

	// Invitations
	InvitationsBase     = APIBase + "/invitations"
	InvitationsSentBase = InvitationsBase + "/sent"

	// Notifications
	NotificationsPath = APIBase + "/notifications"

	// PendingRegistrations
	PendingRegistrationsBase = APIBase + "/pending_registrations"

	// Sessions
	SessionsBase = APIBase + "/sessions"

	// UserProfiles
	UserProfilesBase = APIBase + "/user_profiles"
)

// =============================================================================
// Invitations
// =============================================================================

// InvitationPath returns the path for a specific invitation.
func InvitationPath(invitationID string) string {
	return fmt.Sprintf("%s/%s", InvitationsBase, invitationID)
}

// =============================================================================
// PendingRegistrations
// =============================================================================

// PendingRegistrationApprovePath returns the path to approve for a pendingregistration.
func PendingRegistrationApprovePath(userProfileID string) string {
	return fmt.Sprintf("%s/%s/approve", PendingRegistrationsBase, userProfileID)
}

// PendingRegistrationRejectPath returns the path to reject for a pendingregistration.
func PendingRegistrationRejectPath(userProfileID string) string {
	return fmt.Sprintf("%s/%s/reject", PendingRegistrationsBase, userProfileID)
}

// =============================================================================
// Sessions
// =============================================================================

// SessionArchivePath returns the path to archive for a session.
func SessionArchivePath(sessionID string) string {
	return fmt.Sprintf("%s/%s/archive", SessionsBase, sessionID)
}

// SessionBackupPath returns the path to backup for a session.
func SessionBackupPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/backup", SessionsBase, sessionID)
}

// SessionFilesPath returns the path to files for a session.
func SessionFilesPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/files", SessionsBase, sessionID)
}

// SessionGamePath returns the path to game for a session.
func SessionGamePath(sessionID string) string {
	return fmt.Sprintf("%s/%s/game", SessionsBase, sessionID)
}

// SessionInvitePath returns the path to invite for a session.
func SessionInvitePath(sessionID string) string {
	return fmt.Sprintf("%s/%s/invite", SessionsBase, sessionID)
}

// SessionJoinPath returns the path to join for a session.
func SessionJoinPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/join", SessionsBase, sessionID)
}

// SessionOrdersPath returns the path to orders for a session.
func SessionOrdersPath(sessionID string, year int) string {
	return fmt.Sprintf("%s/%s/orders/%d", SessionsBase, sessionID, year)
}

// SessionPath returns the path for a specific session.
func SessionPath(sessionID string) string {
	return fmt.Sprintf("%s/%s", SessionsBase, sessionID)
}

// SessionPlayerControlPath returns the path to player control for a session.
func SessionPlayerControlPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/player_control", SessionsBase, sessionID)
}

// SessionPlayerRaceDeletePath returns the path to player race delete for a session.
func SessionPlayerRaceDeletePath(sessionID string, playerRaceID string) string {
	return fmt.Sprintf("%s/%s/player_race/%s", SessionsBase, sessionID, playerRaceID)
}

// SessionPlayerRacePath returns the path to player race for a session.
func SessionPlayerRacePath(sessionID string) string {
	return fmt.Sprintf("%s/%s/player_race", SessionsBase, sessionID)
}

// SessionPlayerRaceReadyPath returns the path to player race ready for a session.
func SessionPlayerRaceReadyPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/player_race/ready", SessionsBase, sessionID)
}

// SessionPlayerSwitchToAIPath returns the path to player switch to a i for a session.
func SessionPlayerSwitchToAIPath(sessionID string, playerOrder int) string {
	return fmt.Sprintf("%s/%s/player/%d/switch_to_ai", SessionsBase, sessionID, playerOrder)
}

// SessionPlayerSwitchToHumanPath returns the path to player switch to human for a session.
func SessionPlayerSwitchToHumanPath(sessionID string, playerOrder int) string {
	return fmt.Sprintf("%s/%s/player/%d/switch_to_human", SessionsBase, sessionID, playerOrder)
}

// SessionPromotePath returns the path to promote for a session.
func SessionPromotePath(sessionID string, userProfileID string) string {
	return fmt.Sprintf("%s/%s/promote/%s", SessionsBase, sessionID, userProfileID)
}

// SessionQuitPath returns the path to quit for a session.
func SessionQuitPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/quit", SessionsBase, sessionID)
}

// SessionReorderPlayersPath returns the path to reorder players for a session.
func SessionReorderPlayersPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/reorder_players", SessionsBase, sessionID)
}

// SessionRulesPath returns the path to rules for a session.
func SessionRulesPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/rules", SessionsBase, sessionID)
}

// SessionTurnLatestPath returns the path to turn latest for a session.
func SessionTurnLatestPath(sessionID string) string {
	return fmt.Sprintf("%s/%s/turn/latest", SessionsBase, sessionID)
}

// SessionTurnPath returns the path to turn for a session.
func SessionTurnPath(sessionID string, year int) string {
	return fmt.Sprintf("%s/%s/turn/%d", SessionsBase, sessionID, year)
}

// =============================================================================
// UserProfiles
// =============================================================================

// UserProfilePath returns the path for a specific userprofile.
func UserProfilePath(userProfileID string) string {
	return fmt.Sprintf("%s/%s", UserProfilesBase, userProfileID)
}

// UserProfileRacePath returns the path to race for a userprofile.
func UserProfileRacePath(userProfileID string, raceID string) string {
	return fmt.Sprintf("%s/%s/races/%s", UserProfilesBase, userProfileID, raceID)
}

// UserProfileRacesPath returns the path to races for a userprofile.
func UserProfileRacesPath(userProfileID string) string {
	return fmt.Sprintf("%s/%s/races", UserProfilesBase, userProfileID)
}

// UserProfileResetApikeyPath returns the path to reset apikey for a userprofile.
func UserProfileResetApikeyPath(userProfileID string) string {
	return fmt.Sprintf("%s/%s/reset_apikey", UserProfilesBase, userProfileID)
}
